# Generated by Django 3.0.7 on 2020-06-25 20:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(blank=True, default='', max_length=120)),
                ('phot', models.ImageField(upload_to='uploads/')),
                ('fc_max', models.FloatField(default=None, null=True)),
                ('fc_ave', models.FloatField(default=None, null=True)),
                ('tag', models.CharField(blank=True, default='', max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'm_bike',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'm_country',
            },
        ),
        migrations.CreateModel(
            name='Eda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_displacement_area', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'm_eda',
            },
        ),
        migrations.CreateModel(
            name='Fc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.FloatField(default=0)),
                ('distance_bf', models.FloatField(default=0)),
                ('distance_af', models.FloatField(default=0)),
                ('gas_amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(9999)])),
                ('city_ride', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('high_way_ride', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('fc_comment', models.CharField(blank=True, default='', max_length=2000)),
                ('fc_good', models.IntegerField(default=0)),
                ('model_year', models.IntegerField(default=None, null=True)),
                ('phot', models.ImageField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_fc',
            },
        ),
        migrations.CreateModel(
            name='fuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'db_table': 'm_fuel_type',
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker_name_jp', models.CharField(blank=True, default='', max_length=150)),
                ('maker_name_en', models.CharField(blank=True, default='', max_length=150)),
                ('country_id', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'm_maker',
            },
        ),
        migrations.CreateModel(
            name='FcComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.Fc')),
            ],
            options={
                'db_table': 't_fc_commnet',
            },
        ),
    ]
