# Generated by Django 3.1 on 2020-08-09 07:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bike_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bike_name', models.CharField(blank=True, default='', max_length=120)),
                ('phot', models.ImageField(default=None, null=True, upload_to='uploads/')),
                ('fc_max', models.FloatField(default=None, null=True)),
                ('fc_ave', models.FloatField(default=None, null=True)),
                ('tag', models.CharField(blank=True, default='', max_length=1500)),
                ('engine_displacement', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'fc_bike',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fc_country',
            },
        ),
        migrations.CreateModel(
            name='Eda',
            fields=[
                ('eda_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine_displacement_area', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fc_eda',
            },
        ),
        migrations.CreateModel(
            name='Fc',
            fields=[
                ('fc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fc', models.FloatField(default=0)),
                ('distance_bf', models.FloatField(default=0)),
                ('distance_af', models.FloatField(default=0)),
                ('fc_user_official', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('phot_id', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('gas_amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(9999)])),
                ('city_ride', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('high_way_ride', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('fc_comment', models.TextField(blank=True, default='', max_length=2000)),
                ('fc_good', models.IntegerField(default=0)),
                ('model_year', models.IntegerField(default=None, null=True)),
                ('phot', models.ImageField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.bike')),
            ],
            options={
                'db_table': 'fc',
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('fuel_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fuel', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'db_table': 'fc_fuel_type',
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('maker_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maker_name_jp', models.CharField(blank=True, default='', max_length=150)),
                ('maker_name_en', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.country')),
            ],
            options={
                'db_table': 'fc_maker',
            },
        ),
        migrations.CreateModel(
            name='FcComment',
            fields=[
                ('fc_comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.fc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fc_commnet',
            },
        ),
        migrations.AddField(
            model_name='fc',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.fueltype'),
        ),
        migrations.AddField(
            model_name='fc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bike',
            name='engine_displacement_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.eda'),
        ),
        migrations.AddField(
            model_name='bike',
            name='fc_max_user_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bike',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.maker'),
        ),
    ]
