# Generated by Django 3.0.7 on 2020-06-25 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuel_consumption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fccomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fc',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.Bike'),
        ),
        migrations.AddField(
            model_name='fc',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.fuelType'),
        ),
        migrations.AddField(
            model_name='fc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bike',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.Country'),
        ),
        migrations.AddField(
            model_name='bike',
            name='engine_displacement_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.Eda'),
        ),
        migrations.AddField(
            model_name='bike',
            name='fc_max_user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bike',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.Maker'),
        ),
    ]
