# Generated by Django 3.0.7 on 2020-06-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_consumption', '0002_auto_20200626_0531'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bike',
            table='fc_bike',
        ),
        migrations.AlterModelTable(
            name='country',
            table='fc_country',
        ),
        migrations.AlterModelTable(
            name='eda',
            table='fc_eda',
        ),
        migrations.AlterModelTable(
            name='fc',
            table='fc',
        ),
        migrations.AlterModelTable(
            name='fccomment',
            table='fc_commnet',
        ),
        migrations.AlterModelTable(
            name='fueltype',
            table='fc_fuel_type',
        ),
        migrations.AlterModelTable(
            name='maker',
            table='fc_maker',
        ),
    ]
