# Generated by Django 3.0.8 on 2020-07-16 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuel_consumption', '0004_bike_engine_displacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='fc_max_user_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bike',
            name='phot',
            field=models.ImageField(default=None, null=True, upload_to='uploads/'),
        ),
    ]
