# Generated by Django 3.0.8 on 2020-07-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_consumption', '0005_auto_20200716_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
