# Generated by Django 3.0.8 on 2020-07-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_consumption', '0006_auto_20200716_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='fc',
            name='fc_user_official',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
