# Generated by Django 3.0.8 on 2020-07-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_consumption', '0008_fc_phot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fc',
            name='fc_user_official',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='fc',
            name='phot_id',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
