# Generated by Django 3.0.8 on 2020-07-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_consumption', '0009_auto_20200716_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fc',
            name='fc_comment',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
