# Generated by Django 3.0.8 on 2020-08-04 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_consumption', '0010_auto_20200716_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='maker',
            name='country',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.Country'),
        ),
        migrations.AlterField(
            model_name='fc',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.FuelType'),
        ),
    ]
