# Generated by Django 3.1 on 2020-08-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_consumption', '0011_auto_20200804_1402'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='bike',
        #     name='country',
        # ),
        # migrations.RemoveField(
        #     model_name='maker',
        #     name='country_id',
        # ),
        migrations.AlterField(
            model_name='maker',
            name='country',
            field=models.ForeignKey(
                blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.country'),
        ),
    ]
