# Generated by Django 3.2.5 on 2021-07-15 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import seller.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuel_consumption', '0012_auto_20201210_2339'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_alter_companyusergroup_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.CharField(choices=[('MOTO', 'MotorBike')], default='MOTO', max_length=5)),
                ('color', models.CharField(choices=[('#2DC200', 'GREEN'), ('#F2340A', 'ED'), ('#FFFE02', 'YELLOW'), ('#E5E5E5', 'SILVER'), ('#FFFFFF', 'WHITE'), ('#000000', 'BLACK'), ('#FB9AFF', 'PINK'), ('#015CFF', 'BLUE'), ('#9E9E9E', 'GRAY'), ('', 'ANOTHER')], default='', max_length=10)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('model_year', models.IntegerField(default=0)),
                ('vehicle_inspection', models.DateField()),
                ('mileage', models.IntegerField(default=0)),
                ('displacement', models.IntegerField(default=0)),
                ('electric_power', models.IntegerField(default=0)),
                ('custom', models.BooleanField(default=False)),
                ('abs', models.BooleanField(default=False)),
                ('sel_on_web', models.BooleanField(default=False)),
                ('led', models.BooleanField(default=False)),
                ('maker_warranty', models.BooleanField(default=False)),
                ('seller_warranty', models.BooleanField(default=False)),
                ('etc', models.BooleanField(default=False)),
                ('navigation', models.BooleanField(default=False)),
                ('fi', models.BooleanField(default=False)),
                ('four_storoke', models.BooleanField(default=False)),
                ('mt', models.BooleanField(default=False)),
                ('reimport', models.BooleanField(default=False)),
                ('repaired', models.BooleanField(default=False)),
                ('free_oil_change', models.BooleanField(default=False)),
                ('free_maintenance', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('electric_bike', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.bike')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('product_image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owned_featured_image', django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1920, 1080], upload_to=seller.models.ProductImages.get_upload_path)),
                ('thumbnail_image', django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[320, 180], upload_to=seller.models.ProductImages.get_thumbnail_upload_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='seller.products')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
        migrations.CreateModel(
            name='ProductComments',
            fields=[
                ('product_comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='seller.products')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_comments',
            },
        ),
    ]
