# Generated by Django 3.2.5 on 2021-07-15 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20210715_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomments',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='seller.products'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seller.products'),
        ),
    ]
