# Generated by Django 3.2.5 on 2021-07-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20210715_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='moto',
            new_name='bike',
        ),
    ]
