# Generated by Django 3.2.5 on 2021-07-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_rename_moto_products_bike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='bike',
            new_name='moto',
        ),
    ]
