# Generated by Django 3.0.8 on 2020-07-11 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(blank=True, default='div', max_length=150)),
                ('tag_id_name', models.CharField(blank=True, default='', max_length=50)),
                ('tag_class_name', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'news_content_tag',
            },
        ),
        migrations.CreateModel(
            name='MainCategoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news_main_category_tag',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('url', models.URLField()),
                ('published_at', models.DateTimeField()),
                ('featured_image', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='TargetSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('rss_url', models.URLField()),
                ('url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_tag', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='news.ContentTag')),
            ],
            options={
                'db_table': 'news_target_site',
            },
        ),
        migrations.CreateModel(
            name='TagMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_category_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.MainCategoryTag')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
            options={
                'db_table': 'news_tag_map',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_category_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.MainCategoryTag')),
            ],
            options={
                'db_table': 'news_sub_category_tag',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.TargetSite'),
        ),
    ]
