# Generated by Django 2.2 on 2020-08-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategorytag',
            options={'ordering': ('tag_counter',)},
        ),
    ]
