# Generated by Django 3.0.8 on 2020-07-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsite',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
