# Generated by Django 3.0.8 on 2020-07-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_targetsite_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorytag',
            name='tag_counter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
