# Generated by Django 2.2 on 2020-08-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200809_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategorytag',
            options={'ordering': ('-tag_counter',)},
        ),
    ]
