# Generated by Django 3.0.8 on 2020-07-15 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_subcategorytag_tag_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorytag',
            name='main_category_tag',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='news.MainCategoryTag'),
        ),
    ]
