# Generated by Django 3.0.8 on 2020-07-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200715_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='published_at',
        ),
    ]
