# Generated by Django 3.0.8 on 2020-07-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_news_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorytag',
            name='is_tag',
            field=models.BooleanField(default=True),
        ),
    ]
