# Generated by Django 3.0.8 on 2020-07-15 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_subcategorytag_is_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagmap',
            name='main_category_tag',
        ),
        migrations.AddField(
            model_name='tagmap',
            name='sub_category_tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.SubCategoryTag'),
        ),
        migrations.AlterModelTable(
            name='tagmap',
            table='news_main_category_tag_map',
        ),
    ]
