# Generated by Django 3.0.8 on 2020-07-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200716_0119'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tagmap',
            table='news_category_tag_map',
        ),
    ]
