# Generated by Django 3.0.8 on 2020-07-15 16:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200716_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryTagMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
            options={
                'db_table': 'news_sub_category_tag_map',
            },
        ),
        migrations.AlterField(
            model_name='subcategorytag',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='TagMap',
        ),
        migrations.AddField(
            model_name='subcategorytagmap',
            name='sub_category_tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.SubCategoryTag'),
        ),
    ]
