# Generated by Django 3.0.8 on 2020-07-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_consumption', '0010_auto_20200716_2010'),
        ('news', '0011_subcategorytag_related_of_bike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorytag',
            name='related_of_bike',
        ),
        migrations.AddField(
            model_name='subcategorytag',
            name='related_of_maker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.Maker'),
        ),
    ]
