# Generated by Django 3.0.8 on 2020-07-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200716_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
