# Generated by Django 3.0.8 on 2020-07-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_news_summary'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subcategorytag',
            table='news_sub_category_tag_bk',
        ),
    ]
