# Generated by Django 3.0.8 on 2020-07-16 14:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_consumption', '0010_auto_20200716_2010'),
        ('news', '0014_auto_20200716_2308'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subcategorytag',
            table='news_sub_category_tag',
        ),
        migrations.CreateModel(
            name='SubCategoryTagBk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('tag_counter', models.IntegerField(blank=True, default=0)),
                ('is_tag', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_category_tag', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.MainCategoryTag')),
                ('related_of_maker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.Maker')),
            ],
            options={
                'db_table': 'news_sub_category_tag_bk',
            },
        ),
    ]
