# Generated by Django 3.0.8 on 2020-07-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20200716_2311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategoryTagBk',
        ),
    ]
