# Generated by Django 3.0.7 on 2021-07-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_bike', '0003_auto_20210630_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='expired_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
