# Generated by Django 3.0.7 on 2021-07-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell_bike', '0004_company_expired_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='expired_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='company',
            name='stripe_customer_id',
        ),
    ]
