# Generated by Django 3.0.7 on 2021-07-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_bike', '0005_auto_20210704_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='old_company',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='old_company',
            name='address',
        ),
        migrations.AddField(
            model_name='old_company',
            name='building',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='old_company',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='old_company',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='old_company',
            name='street',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='old_company',
            name='prefecture',
            field=models.TextField(default=''),
        ),
    ]
