# Generated by Django 3.0.7 on 2020-09-04 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationSettings',
            fields=[
                ('push_notification_settings_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.URLField(blank=True, default='div', max_length=150)),
                ('token', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'push_notification_settings',
            },
        ),
    ]
