# Generated by Django 3.0.7 on 2020-09-08 01:53

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('native_app_notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationTokens',
            fields=[
                ('push_notification_tokens_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'push_notification_tokens',
            },
        ),
        migrations.RemoveField(
            model_name='pushnotificationsettings',
            name='token',
        ),
        migrations.AddField(
            model_name='pushnotificationsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pushnotificationsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
