# Generated by Django 3.0.7 on 2020-10-03 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('native_app_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushnotificationtokens',
            options={'ordering': ['-created_at']},
        ),
    ]
