# Generated by Django 3.0.7 on 2020-09-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('native_app_notification', '0002_auto_20200908_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotificationsettings',
            name='push_notification_settings_id',
        ),
        migrations.AddField(
            model_name='pushnotificationsettings',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
