# Generated by Django 3.0.7 on 2020-10-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('native_app_notification', '0002_auto_20201003_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotificationsettings',
            name='push_notification_send_unit',
            field=models.IntegerField(default=1),
        ),
    ]
