# Generated by Django 3.0.7 on 2020-09-08 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('native_app_notification', '0003_auto_20200908_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushNotificationSettings',
        ),
    ]
