# Generated by Django 3.0.7 on 2020-09-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('native_app_notification', '0004_delete_pushnotificationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(blank=True, default='div', max_length=150)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'push_notification_settings',
            },
        ),
    ]
