# Generated by Django 3.0.7 on 2021-07-04 07:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sell_bike', '0005_auto_20210704_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('plan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('monthly_max_bike_register', models.IntegerField(default=0)),
                ('max_company_register', models.IntegerField(default=0)),
                ('publish_ads', models.TextField()),
                ('publish_news', models.TextField()),
                ('stripe_price_id', models.TextField()),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('subscription_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.TextField()),
                ('expired_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell_bike.Company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.Plans')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
