# Generated by Django 3.0.7 on 2021-07-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='expired_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
