# Generated by Django 3.2.5 on 2021-07-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_capability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='publish_ads',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='publish_news',
        ),
    ]
