# Generated by Django 3.1 on 2020-08-09 07:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuel_consumption', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('content_tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_type', models.CharField(blank=True, default='div', max_length=150)),
                ('tag_id_name', models.CharField(blank=True, default='', max_length=50)),
                ('tag_class_name', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'news_content_tag',
            },
        ),
        migrations.CreateModel(
            name='MainCategoryTag',
            fields=[
                ('main_category_tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news_main_category_tag',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('summary', models.CharField(blank=True, default='', max_length=150)),
                ('url', models.URLField()),
                ('featured_image', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryTag',
            fields=[
                ('sub_category_tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('tag_counter', models.IntegerField(blank=True, default=0)),
                ('is_tag', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_category_tag', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.maincategorytag')),
                ('related_of_maker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fuel_consumption.maker')),
            ],
            options={
                'db_table': 'news_sub_category_tag',
            },
        ),
        migrations.CreateModel(
            name='TargetSite',
            fields=[
                ('target_site_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('rss_url', models.URLField()),
                ('url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_tag', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='news.contenttag')),
            ],
            options={
                'db_table': 'news_target_site',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryTagMap',
            fields=[
                ('sub_category_tag_map_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
                ('sub_category_tag', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.subcategorytag')),
            ],
            options={
                'db_table': 'news_sub_category_tag_map',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.targetsite'),
        ),
    ]
