# Generated by Django 2.2 on 2020-08-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200809_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategorytag',
            options={'ordering': ('-tag_counter', '-main_category_tag')},
        ),
    ]
