# Generated by Django 3.0.7 on 2020-08-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200816_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategorytag',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, unique=True),
        ),
    ]
