# Generated by Django 3.0.7 on 2020-08-31 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_consumption', '0003_auto_20200830_1142'),
        ('news', '0008_auto_20200827_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorytag',
            name='main_category_tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_tag', to='news.MainCategoryTag'),
        ),
        migrations.AlterField(
            model_name='subcategorytag',
            name='related_of_maker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_tag', to='fuel_consumption.Maker'),
        ),
        migrations.AlterField(
            model_name='subcategorytagmap',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_tag_map', to='news.News'),
        ),
        migrations.AlterField(
            model_name='subcategorytagmap',
            name='sub_category_tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_tag_map', to='news.SubCategoryTag'),
        ),
    ]
