# Generated by Django 3.0.7 on 2020-08-31 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200831_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategorytagmap',
            old_name='news_list',
            new_name='news',
        ),
    ]
