# Generated by Django 3.0.7 on 2020-09-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200903_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategorytag',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maincategorytag',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
