# Generated by Django 3.0.7 on 2020-09-08 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20200905_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincategorytag',
            old_name='is_show',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='maincategorytag',
            old_name='order_number',
            new_name='ordering_number',
        ),
    ]
