# Generated by Django 3.0.7 on 2020-09-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20200908_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategorytag',
            name='push_counter',
            field=models.IntegerField(default=0),
        ),
    ]
