# Generated by Django 3.0.7 on 2020-09-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_maincategorytag_push_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetsite',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
