# Generated by Django 3.0.7 on 2020-11-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20200914_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
