# Generated by Django 3.0.7 on 2020-12-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_news_is_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsite',
            name='is_there_another_sourse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='targetsite',
            name='sourse_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='targetsite',
            name='rss_url',
            field=models.URLField(default=''),
        ),
    ]
