# Generated by Django 3.0.7 on 2020-12-04 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20201205_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetsite',
            name='content_tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.ContentTag'),
        ),
    ]
