# Generated by Django 3.0.7 on 2020-12-04 18:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20201205_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourseSite',
            fields=[
                ('sourse_site_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('sorse_url', models.URLField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sourse_site',
                'ordering': ('created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='targetsite',
            name='sourse_name',
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='sourse_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.SourseSite'),
        ),
    ]
