# Generated by Django 3.0.7 on 2020-12-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20201205_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsite',
            name='deactive',
            field=models.BooleanField(default=False),
        ),
    ]
