# Generated by Django 3.0.7 on 2020-12-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_targetsite_deactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='sourse_site',
            new_name='source_site',
        ),
        migrations.RenameField(
            model_name='soursesite',
            old_name='sourse_site_id',
            new_name='source_site_id',
        ),
        migrations.RenameField(
            model_name='targetsite',
            old_name='is_there_another_sourse',
            new_name='is_there_another_source',
        ),
        migrations.AlterModelTable(
            name='soursesite',
            table='source_site',
        ),
    ]
