# Generated by Django 3.0.7 on 2020-12-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20201205_0401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soursesite',
            old_name='sorse_url',
            new_name='sorce_url',
        ),
    ]
