# Generated by Django 3.0.7 on 2020-12-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_auto_20201205_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='owned_featured_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/news/featured_image/'),
        ),
    ]
