# Generated by Django 3.0.7 on 2020-12-10 07:44

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_news_owned_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thumbnail_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[200, 150], upload_to='media/news/thumbnail_image/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='owned_featured_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1920, 1080], upload_to='media/news/featured_image/'),
        ),
    ]
