# Generated by Django 3.0.7 on 2021-01-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20201210_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_youtube',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='targetsite',
            name='is_youtube',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='targetsite',
            name='youtube_query',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
