# Generated by Django 3.0.7 on 2021-01-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_news_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsite',
            name='hide_post',
            field=models.BooleanField(default=False),
        ),
    ]
