# Generated by Django 2.2 on 2020-08-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
