# Generated by Django 3.0.7 on 2021-06-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.TextField(),
        ),
    ]
