# Generated by Django 3.2.5 on 2021-07-17 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210710_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invited_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
