# Generated by Django 3.0.7 on 2020-08-30 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_consumption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fc',
            name='gas_amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='fc',
            name='phot',
            field=models.ImageField(blank=True, default='', upload_to='uploads/'),
        ),
    ]
