# Generated by Django 3.0.7 on 2020-08-30 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_consumption', '0002_auto_20200830_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fc',
            name='fc',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
