# Generated by Django 3.0.7 on 2020-09-10 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuel_consumption', '0006_auto_20200908_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fc',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fc', to='fuel_consumption.Bike'),
        ),
        migrations.AlterField(
            model_name='fc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fc', to=settings.AUTH_USER_MODEL),
        ),
    ]
