# Generated by Django 3.0.7 on 2020-09-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_consumption', '0008_auto_20200910_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fc',
            options={'ordering': ['-created_at']},
        ),
    ]
