# Generated by Django 3.0.7 on 2020-10-03 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuel_consumption', '0009_auto_20200911_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eda',
            options={'ordering': ['-engine_displacement_area']},
        ),
        migrations.AlterField(
            model_name='bike',
            name='fc_ave',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='fc_max',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='fc_max_user_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bike',
            name='phot',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
