# Generated by Django 3.0.7 on 2020-12-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_consumption', '0010_auto_20201003_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='phot',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/bikes/origin/'),
        ),
        migrations.AlterField(
            model_name='fc',
            name='phot',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/bikes/user/'),
        ),
    ]
