# Generated by Django 3.0.7 on 2020-12-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchkeyword',
            name='is_active',
        ),
    ]
