# Generated by Django 3.0.7 on 2020-12-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_remove_searchkeyword_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followinfo',
            options={'ordering': ('-updated_at',)},
        ),
    ]
