# Generated by Django 3.0.7 on 2020-06-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'ユーザー一覧'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
    ]
