# Generated by Django 3.2.5 on 2021-07-13 15:00

import company.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owned_featured_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1920, 1080], upload_to=company.models.Company.get_upload_path),
        ),
        migrations.AddField(
            model_name='company',
            name='thumbnail_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format='JPEG', keep_meta=True, null=True, quality=20, size=[320, 180], upload_to=company.models.Company.get_thumbnail_upload_path),
        ),
    ]
