# Generated by Django 3.2.5 on 2021-07-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210714_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyusergroup',
            name='permission',
            field=models.TextField(choices=[(10, 'admin'), (20, 'editor'), (30, 'viewer')]),
        ),
    ]
