# Generated by Django 3.2.5 on 2021-07-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_companyusergroup_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyusergroup',
            name='permission',
            field=models.IntegerField(choices=[(10, 'admin'), (20, 'editor'), (30, 'viewer')], default=30),
        ),
    ]
